# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24f01d23f246c5efd9801b5159806905964dfe28c9972dcdfdedea1e37f1dc44fa840f4a7bbc27c2362e80464bd318f5f964914f313b8e4eb410c9fcf9f93930

test:
  secret_key_base: ddafd03567b30a4959c6fcf827c85bf563923f47f27a5cb4a3f8d75c4220802a9bb123f1a97daf6a7426a8bc8434de2dbf74e4ce362cce66aef3e2fe98a6b85b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
